MedioClinic/Models/InlineEditors/ImageUploaderEditor/ImageUploaderEditorViewModel.cs
namespace MedioClinic.Models.InlineEditors
{
    public class ImageUploaderEditorViewModel : InlineEditorViewModel
    {
        public bool HasImage { get; set; }

        public MediaLibraryViewModel MediaLibraryViewModel { get; set; }
    }
}

MedioClinic/Models/InlineEditors/InlineEditorViewModel.cs
namespace MedioClinic.Models.InlineEditors
{
    /// <summary>
    /// Base class for inline editor view models.
    /// </summary>
    public abstract class InlineEditorViewModel
    {
        /// <summary>
        /// Name of the widget property to edit.
        /// </summary>
        public string PropertyName { get; set; }
    }
}

MedioClinic/Models/InlineEditors/SlideshowEditor/SlideshowEditorViewModel.cs
using System.Collections.Generic;

using Business.Dto.MediaLibrary;

namespace MedioClinic.Models.InlineEditors
{
    public class SlideshowEditorViewModel : InlineEditorViewModel
    {
        public string SwiperId { get; set; }
        public MediaLibraryViewModel MediaLibraryViewModel { get; set; }
        public IEnumerable<MediaLibraryFileDto> Images { get; set; }
    }
}

MedioClinic/Models/InlineEditors/TextEditor/TextEditorViewModel.cs
namespace MedioClinic.Models.InlineEditors
{
    public class TextEditorViewModel : InlineEditorViewModel
    {
        public string Text { get; set; }
    }
}

MedioClinic/Controllers/InlineEditors/ImageUploaderController.cs
using System;
using System.Web;
using System.Web.Mvc;

using MedioClinic.Utils;

namespace MedioClinic.Controllers.Widgets
{
    public class ImageUploaderController : Controller
    {
        protected string TempPath => $"{Server.MapPath(@"~\")}App_Data\\Temp\\ImageUploaderEditor";

        protected IFileManager FileManager { get; }

        protected IErrorHelper ErrorHelper { get; }

        public ImageUploaderController(IFileManager fileManager, IErrorHelper errorHandler)
        {
            FileManager = fileManager ?? throw new ArgumentNullException(nameof(fileManager));
            ErrorHelper = errorHandler ?? throw new ArgumentNullException(nameof(errorHandler));
        }

        // POST: ImageUploader/Upload/[mediaLibraryName, mediaLibrarySiteName]
        [HttpPost]
        public ActionResult Upload(string mediaLibraryName, string mediaLibrarySiteName)
        {
            ErrorHelper.CheckEditMode(HttpContext, nameof(ImageUploaderController.Upload));
            var imageGuid = Guid.Empty;

            if (Request.Files[0] is HttpPostedFileWrapper file)
            {
                try
                {
                    imageGuid = FileManager.AddMediaLibraryFile(file, TempPath, libraryName: mediaLibraryName, librarySiteName: mediaLibrarySiteName, checkPermisions: true);
                }
                catch (Exception ex)
                {
                    var result = ErrorHelper.HandleException(
                        nameof(ImageUploaderController), 
                        nameof(Upload), 
                        ex, 
                        ErrorHelper.UnprocessableStatusCode);

                    return result;
                }

                return Json(new { guid = imageGuid }); 
            }

            return new HttpStatusCodeResult(ErrorHelper.UnprocessableStatusCode);
        }
    }
}

MedioClinic/Views/Shared/InlineEditors/_ImageUploader.cshtml
@using MedioClinic.Models.InlineEditors
@model ImageUploaderEditorViewModel

@{
    string GetContainerClass() =>
        Model.HasImage == true ? "kn-image-uploader-container" : "kn-image-uploader-empty-container";

    // Gets the URL to the ImageUploaderController's action.
    HtmlString GetActionUrl()
    {
        var url = Url.Kentico().AuthenticateUrl(Url.Action("Upload", "ImageUploader", new
        {
            mediaLibraryName = Model.MediaLibraryViewModel.LibraryName,
            mediaLibrarySiteName = Model.MediaLibraryViewModel.LibrarySiteName
        }), false);

        return url;
    }
}

@using (Html.Kentico().BeginInlineEditor("image-uploader-editor", Model.PropertyName,
    new
    {
        @class = "kn-image-uploader-editor",
        data_upload_url = GetActionUrl().ToString(),
        data_allowed_image_extensions = string.Join(",", Model.MediaLibraryViewModel.AllowedImageExtensions)
    }))
{
    <div class="@GetContainerClass()">
        <div class="dz-uploader">
            <div class="dz-message top">
                @Html.Raw(Html.Localize("ImageUploader.Dropzone.DropText"))
            </div>
        </div>
    </div>
}

MedioClinic/Views/Shared/InlineEditors/_SlideshowEditor.cshtml
@using MedioClinic.Models.InlineEditors
@model SlideshowEditorViewModel

@{ 
    string SerializeGuids(IEnumerable<Guid> guids) =>
        string.Concat(guids.Select(guid => guid.ToString() + ";"));
}

@using (Html.Kentico().BeginInlineEditor("slideshow-editor", Model.PropertyName,
    new
    {
        @class = "kn-slideshow-editor",
        data_swiper_guid = Model.SwiperId,
        data_media_library_name = Model.MediaLibraryViewModel.LibraryName,
        data_image_guids = SerializeGuids(Model.Images.Select(image => image.Guid)),
        data_allowed_image_extensions = string.Join(";", Model.MediaLibraryViewModel.AllowedImageExtensions)
    }))
{
    <ul class="kn-slideshow-buttons">
        <li>
            <button class="kn-swiper-plus">+</button>
        </li>
        <li>
            <button class="kn-swiper-minus">-</button>
        </li>
    </ul>
}

MedioClinic/Views/Shared/InlineEditors/_TextEditor.cshtml
@model MedioClinic.Models.InlineEditors.TextEditorViewModel

@using (Html.Kentico().BeginInlineEditor("text-editor", Model.PropertyName,
    new
    {
        @class = "text-editor"
    }))
{
    @Html.Raw(Model.Text)
}