MedioClinic/Models/UserMessage.cs
namespace MedioClinic.Models
{
    public class UserMessage
    {
        public MessageType MessageType { get; set; }

        public string Message { get; set; }

        public bool DisplayAsRaw { get; set; }
    }
}

MedioClinic/Controllers/NotFoundController.cs
using System.Web.Mvc;
using Business.DependencyInjection;

namespace MedioClinic.Controllers
{
    public class NotFoundController : BaseController
    {

        public NotFoundController(IBusinessDependencies dependencies) : base(dependencies)
        {
        }

        public ActionResult Index()
        {
            Response.StatusCode = 404;

            var model = GetPageViewModel("Not found");

            return View(model);
        }
       
    }
}

MedioClinic/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

using Business.Attributes;
using Business.DependencyInjection;
using Business.Identity.Models;
using MedioClinic.Config;
using MedioClinic.Models;
using MedioClinic.Models.Profile;
using MedioClinic.Utils;

namespace MedioClinic.Controllers
{
    // In production, use [RequireHttps].
    [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
    public class ProfileController : BaseController
    {
        public IProfileManager ProfileManager { get; }

        public ProfileController(
            IProfileManager profileManager,
            IBusinessDependencies dependencies) : base(dependencies)
        {
            ProfileManager = profileManager ?? throw new ArgumentNullException(nameof(profileManager));
        }

        // GET: Profile
        [MedioClinicAuthorize(Roles = Roles.Doctor | Roles.Patient, SiteName = AppConfig.Sitename)]
        public async Task<ActionResult> Index() =>
            await GetProfileAsync();

        // POST: Profile
        [MedioClinicAuthorize(Roles = Roles.Doctor | Roles.Patient, SiteName = AppConfig.Sitename)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(PageViewModel<IUserViewModel> uploadModel)
        {
            var message = ConcatenateContactAdmin("Error.Message");

            if (ModelState.IsValid)
            {
                var profileResult = await ProfileManager.PostProfileAsync(uploadModel.Data, Request.RequestContext);

                switch (profileResult.ResultState)
                {
                    case PostProfileResultState.UserNotFound:
                        message = ConcatenateContactAdmin("Controllers.Profile.Index.UserNotFound.Message");
                        break;
                    case PostProfileResultState.UserNotMapped:
                    case PostProfileResultState.UserNotUpdated:
                        message = ConcatenateContactAdmin("Controllers.Profile.Index.UserNotUpdated.Message");
                        break;
                    case PostProfileResultState.UserUpdated:
                        message = Localize("Controllers.Profile.Index.UserUpdated.Message");
                        break;
                }

                var model = GetPageViewModel(profileResult.Data.UserViewModel, profileResult.Data.PageTitle ?? ErrorTitle, message);

                return View(model);
            }

            return await GetProfileAsync();
        }

        /// <summary>
        /// Displays the user profile.
        /// </summary>
        /// <returns>Either a user profile page, or a not-found page.</returns>
        protected async Task<ActionResult> GetProfileAsync()
        {
            var userName = HttpContext.User?.Identity?.Name;

            if (!string.IsNullOrEmpty(userName))
            {
                var profileResult = await ProfileManager.GetProfileAsync(userName, Request.RequestContext);

                if (profileResult.Success)
                {
                    var model = GetPageViewModel(profileResult.Data.UserViewModel, profileResult.Data.PageTitle);

                    return View(model);
                }
            }

            return UserNotFound();
        }

        /// <summary>
        /// Displays a not-found page.
        /// </summary>
        /// <returns>A not-found page.</returns>
        protected ActionResult UserNotFound()
        {
            var message = Dependencies.LocalizationService.Localize("General.UserNotFound");

            return View("UserMessage", GetPageViewModel(ErrorTitle, message, messageType: MessageType.Error));
        }
    }
}

MedioClinic/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

@*<h1>NotFound</h1>*@

<div class="section">
    <div class="container">
        <!-- Not found section -->
        <div class="row">
            <div class="col s12 m12">
                <h1>404 Page not found</h1>
            </div>
            <div class="col l8 m12 s12">
                <p>
                    Sorry, but the page you are looking for can't be found. Please go back to the
                    <a href="index.html">home page</a>.
                </p>
                <img class="responsive-img" src="assets/404 photo/896212130.jpg" alt="upset doctor page not found">
            </div>
        </div>
    </div>
</div>

MedioClinic/Views/Shared/UserMessage.cshtml
@model MedioClinic.Models.PageViewModel

<div class="container">
    <div class="row">
        <h4>@Html.DisplayFor(m => m.Metadata.Title)</h4>
        @Html.DisplayFor(m => m.UserMessage)
    </div>
</div>

MedioClinic/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization

@model MedioClinic.Models.PageViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title>@Model.Metadata.Title | @Model.Metadata.CompanyName</title>
    <link rel="shortcut icon" type="image/png" href="~/Content/images/Logo/favicon.png" />

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
          crossorigin="anonymous">
    @Styles.Render("~/bundles/master-css")
    @RenderSection("Styles", required: false)
</head>
<body>

    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="@Url.Action("Index", "Home")" class="brand-logo">
                <img class="kn-logo" src="~/Content/images/Logo/Logoic.png" alt="">
                <span>@Model.Metadata.CompanyName</span>
            </a>
            <!-- Languages structure -->
            @if (Model.Cultures != null)
            {
                <ul id="langs" class="dropdown-content">
                    @foreach (var culture in Model.Cultures)
                    {
                        var currentRouteValues = new RouteValueDictionary(
                            Url.RequestContext.RouteData.Values
                            )
                        { ["culture"] = culture.CultureCode };
                        <li>
                            <a href="@Url.Action(
                                         ViewContext.RouteData.Values["action"]?.ToString(),
                                         ViewContext.RouteData.Values["controller"]?.ToString(),
                                            currentRouteValues)">
                                @culture.CultureShortName
                            </a>
                        </li>
                    }
                </ul>
            }

            @if (Context.User.Identity.IsAuthenticated)
            {
                <ul id="user-account" class="dropdown-content">
                    <li><a href="@Url.Action("Index", "Profile")">Profile</a></li>
                    <li><a href="@Url.Action("Signout", "Account")">Sign out</a></li>
                </ul>
            }
            else
            {
                <ul id="user-account" class="dropdown-content">
                    <li><a href="@Url.Action("Register", "Account")">Register</a></li>
                    <li><a href="@Url.Action("Signin", "Account")">Sign in</a></li>
                </ul>
            }

            <ul class="right hide-on-med-and-down">
                @foreach (var menuItem in Model.MenuItems)
                {
                    if (ViewContext.RouteData.Values["controller"]?.ToString().Equals(menuItem.Controller, StringComparison.OrdinalIgnoreCase) ?? false)
                    {
                        <li class="kn-bold">
                            <a href="@Url.Action(menuItem.Action, menuItem.Controller)">@menuItem.Caption</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action(menuItem.Action, menuItem.Controller)">@menuItem.Caption</a>
                        </li>
                    }
                }

                <li>
                    <a class="dropdown-trigger" href="#" data-target="langs">
                        @Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName
                        <i class="fas fa-globe-africa right"></i>
                    </a>
                </li>
                <li>
                    <a class="dropdown-trigger" href="#" data-target="user-account">
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            @Html.Raw(User.Identity.Name)
                        }
                        <i class="fas fa-user-circle right"></i>
                    </a>
                </li>
            </ul>
            <ul id="nav-mobile" class="sidenav">
                @foreach (var menuItem in Model.MenuItems)
                {
                    if (ViewContext.RouteData.Values["controller"]?.ToString().Equals(menuItem.Controller, StringComparison.OrdinalIgnoreCase) ?? false)
                    {
                        <li>
                            <a href="@Url.Action(menuItem.Action, menuItem.Controller)">@menuItem.Caption</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action(menuItem.Action, menuItem.Controller)">@menuItem.Caption</a>
                        </li>
                    }
                }
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger">
                <i class="material-icons">menu</i>
            </a>
        </div>
    </nav>

    @RenderBody()

    <footer class="page-footer blue-grey darken-4">
        <div class="container">
            <div class="row">
                <div class="col l4 s12">
                    @if (Model.Company != null)
                    {
                        <h5 class="white-text">@Html.Localize("Footer.Contact")</h5>
                        <div class="grey-text text-lighten-4">
                            <p class="kn-smaller kn-address">
                                <address>
                                    <strong>@Model.Company.Name</strong>
                                    <br> @Model.Company.PhoneNumber
                                    <br> @Model.Company.Email
                                    <br> @Model.Company.ShortAddress
                                </address>
                            </p>
                        </div>
                    }
                </div>
                <div class="col l4 s12">
                    <h5 class="white-text">@Html.Localize("Footer.FollowUs")</h5>
                    <div class="kn-social">
                        @foreach (var socialLink in Model.SocialLinks)
                        {
                            <a href="@socialLink.Url" title="@socialLink.Title">
                                <img alt="@socialLink.Title" src="@Url.KenticoImageUrl(socialLink.Icon.GetPath())">
                            </a>
                        }
                    </div>
                </div>
                <div class="col l4 s12">
                    <h5 class="white-text">@Html.Localize("Footer.Navigation")</h5>
                    <ul class="kn-smaller">
                        @foreach (var menuItem in Model.MenuItems)
                        {
                            <li>
                                <a class="white-text" href="@Url.Action(menuItem.Action, menuItem.Controller)">@menuItem.Caption</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright white">
            <div class="container">
                <div class="row">
                    <div class="col s12">
                        <div class="blue-grey-text text-darken-2">
                            @Html.Raw(Html.Localize("Footer.BuildWithNote")) Kentico, @DateTime.Now.Year.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    @Scripts.Render("~/bundles/master-scripts")

    <!-- Additional (view specific) scripts-->
    @RenderSection("Scripts", false)


</body>
</html>