MedioClinic/Models/Home/HomeViewModel.cs
using System.Collections.Generic;
using Business.Dto.Company;
using Business.Dto.Home;

namespace MedioClinic.Models.Home
{
    public class HomeViewModel : IViewModel
    {
        public IEnumerable<CompanyServiceDto> CompanyServices { get; set; }

        public HomeSectionDto HomeSection { get; set; }
    }
}

MedioClinic/Controllers/DoctorsController.cs
using System;
using System.Web.Mvc;
using System.Web.UI;
using Business.DependencyInjection;
using Business.Dto.Doctors;
using Business.Repository.Doctor;
using Business.Services.Cache;
using CMS.DocumentEngine.Types.MedioClinic;
using MedioClinic.Models.Doctors;

namespace MedioClinic.Controllers
{
    public class DoctorsController : BaseController
    {
        private IDoctorRepository DoctorRepository { get; }
        private IDoctorSectionRepository DoctorSectionRepository { get; }

        public DoctorsController(
            IBusinessDependencies dependencies,
            IDoctorRepository doctorRepository,
            IDoctorSectionRepository doctorSectionRepository
            ) : base(dependencies)
        {
            DoctorRepository = doctorRepository;
            DoctorSectionRepository = doctorSectionRepository;
        }

        public ActionResult Index()
        {
            var doctorSection = Dependencies.CacheService.Cache(
                () => DoctorSectionRepository.GetDoctorSection(), // Gets data for the DoctorSection if there isn't any cached data (data was invalidated or cache expired)
                60, // Sets caching of data to 60 minutes
                $"{nameof(DoctorsController)}|{nameof(Index)}|{nameof(DoctorSectionDto)}", // cached data identifier
                Dependencies.CacheService.GetNodesCacheDependencyKey(Doctor.CLASS_NAME, CacheDependencyType.All) // cache dependencies
                );

            if (doctorSection == null)
            {
                return HttpNotFound();
            }

            var model = GetPageViewModel(new DoctorsViewModel()
            {
                Doctors = DoctorRepository.GetDoctors(),
                DoctorSection = doctorSection
            }, doctorSection.Header);

            return View(model);
        }

        [OutputCache(Duration = 3600, VaryByParam = "nodeGuid", VaryByCustom = "DefaultSet", Location = OutputCacheLocation.Server)]
        public ActionResult Detail(Guid nodeGuid, string nodeAlias)
        {
            var doctor = DoctorRepository.GetDoctor(nodeGuid);

            if (doctor == null)
            {
                return HttpNotFound();
            }

            // Sets cache dependency on single page based on NodeGUID
            // System clears the cache when given doctor is deleted or edited in Kentico
            Dependencies.CacheService.SetOutputCacheDependency(nodeGuid);

            var model = GetPageViewModel(new DoctorDetailViewModel()
            {
                Doctor = doctor
            }, doctor.FullName);

            return View(model);
        }
    }
}

MedioClinic/Controllers/HomeController.cs
using System.Web.Mvc;
using Business.DependencyInjection;
using Business.Repository.Company;
using Business.Repository.Home;
using MedioClinic.Models.Home;

namespace MedioClinic.Controllers
{
    public class HomeController : BaseController
    {
        private ICompanyServiceRepository CompanyServiceRepository { get; }
        private IHomeSectionRepository HomeSectionRepository { get; }

        public HomeController(
            IBusinessDependencies dependencies, 
            ICompanyServiceRepository companyServiceRepository,
            IHomeSectionRepository homeSectionRepository) : base (dependencies)
        {
            CompanyServiceRepository = companyServiceRepository;
            HomeSectionRepository = homeSectionRepository;
        }

        public ActionResult Index()
        {
            var homeSection = HomeSectionRepository.GetHomeSection();

            if (homeSection == null)
            {
                return HttpNotFound();
            }

            var model = GetPageViewModel(new HomeViewModel()
            {
                CompanyServices = CompanyServiceRepository.GetCompanyServices(),
                HomeSection = homeSection
            }, homeSection.Title);

            return View(model);
        }
    }
}

MedioClinic/Views/Home/Index.cshtml
@using MedioClinic.Models.Home

@model MedioClinic.Models.PageViewModel<HomeViewModel>
    
@if (Model.Data.HomeSection != null)
{
    <div class="section kn-section-top">
        <div class="kn-header-gradient">
            <div class="container kn-header">
                <h1 class="col l10 m4 s12">@Model.Data.HomeSection.Title</h1>
                <div class="row left">
                    <h5 class="col l10 m8 s12 kn-light">
                        @Model.Data.HomeSection.Text
                    </h5>
                </div>
                <div class="row">
                    <div class="left">
                        <a href="@Url.Action("index", "Doctors")" class="kn-btn-doctors btn waves-effect waves-light red darken-3">@Model.Data.HomeSection.LinkText</a>
                        <br>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@if (Model.Data.CompanyServices != null)
{
    <div class="container">
        <div class="section">
            <div class="row">
                @foreach (var service in Model.Data.CompanyServices)
                {<div class="col s12 m4">
                        <div class="icon-block">
                            <img class="kn-icons kn-center" src="@Url.KenticoImageUrl(service.Icon.GetPath())" />
                            <h4 class="center">@service.Header</h4>
                            <p class="light center">
                                @service.Text
                            </p>
                        </div>
                    </div>
                }
            </div>
        </div>
        <br>
        <br>
    </div>

}